---
title: "OCSdata Instructions"
output: rmarkdown::html_vignette
description: >
  How to use OCSdata
vignette: >
  %\VignetteIndexEntry{Instructions}
  %\VignetteEngine{knitr::rmarkdown}
  \usepackage[utf8]{inputenc}
---

This document outlines how the functions in the OCSdata package should be used to access data from [Open Case Studies](https://www.opencasestudies.org/). The 'arguments' section explains all of the inputs necessary for the functions to run and examples of appropriate inputs are given. The 'how to use' section explains the purpose of the functions and gives an example for each. The functions are also connected to the corresponding case study section when applicable. 

## Arguments

### casestudy

All of the OCSdata functions require a case study ID to be input to the `casestudy` argument field. This ID should match with the case study you are intending to download data from. See the table below to see the case study names and their corresponding ID.

| Case Study Name | Case Study ID |  
| --------------- | ------------- |
| [Exploring global patterns of obesity across rural and urban regions](https://www.opencasestudies.org/ocs-bp-rural-and-urban-obesity/) | [ocs-bp-rural-and-urban-obesity](https://github.com/opencasestudies/ocs-bp-rural-and-urban-obesity) |
| [Predicting Annual Air Pollution](https://www.opencasestudies.org/ocs-bp-air-pollution/) | [ocs-bp-air-pollution](https://github.com/opencasestudies/ocs-bp-air-pollution) |
| [Vaping Behaviors in American Youth](https://www.opencasestudies.org/ocs-bp-vaping-case-study/) | [ocs-bp-vaping-case-study](https://github.com/opencasestudies/ocs-bp-vaping-case-study) |
| [Opioids in United States](https://www.opencasestudies.org/ocs-bp-opioid-rural-urban/) | [ocs-bp-opioid-rural-urban](https://github.com/opencasestudies/ocs-bp-opioid-rural-urban) |
| [Influence of Multicollinearity on Measured Impact of Right-to-Carry Gun Laws Part 1](https://www.opencasestudies.org/ocs-bp-RTC-wrangling/) | [ocs-bp-RTC-wrangling](https://github.com/opencasestudies/ocs-bp-RTC-wrangling) |
| [Influence of Multicollinearity on Measured Impact of Right-to-Carry Gun Laws Part 2](https://www.opencasestudies.org/ocs-bp-RTC-analysis/) | [ocs-bp-RTC-analysis](https://github.com/opencasestudies/ocs-bp-RTC-analysis) |
| [Disparities in Youth Disconnection](https://www.opencasestudies.org/ocs-bp-youth-disconnection/) | [ocs-bp-youth-disconnection](https://github.com/opencasestudies/ocs-bp-youth-disconnection) |
| [Mental Health of American Youth](https://www.opencasestudies.org/ocs-bp-youth-mental-health/) | [ocs-bp-youth-mental-health](https://github.com/opencasestudies/ocs-bp-youth-mental-health) |
| [School Shootings in the United States](https://www.opencasestudies.org/ocs-bp-school-shootings-dashboard/) | [ocs-bp-school-shootings-dashboard](https://github.com/opencasestudies/ocs-bp-school-shootings-dashboard) |
| [Exploring CO2 emissions across time](https://www.opencasestudies.org/ocs-bp-co2-emissions/) | [ocs-bp-co2-emissions](https://github.com/opencasestudies/ocs-bp-co2-emissions) |
| [Exploring global patterns of dietary behaviors associated with health risk](https://www.opencasestudies.org/ocs-bp-diet/) | [ocs-bp-diet](https://github.com/opencasestudies/ocs-bp-diet) |

### outpath

All of the functions also have an `outpath` argument to specify where the files should be downloaded to. This argument defaults to `NULL` which will ask you to specify and confirm a download location interactively, suggesting your current working directory as an option. If the session is not interactive, an error message is returned that `outpath` must be specified.

### fork_repo

This is a logical argument and only used for `clone_ocs()`. `FALSE` will clone the repo, while `TRUE` will fork the repo and then clone the fork. Defaults to `NA` which will fork or clone based on your repository permissions. 

## How to Use

The following examples illustrate all of the different functions and how you can use them to stop and start at different sections of the case study. These examples will download the data into temporary directories to avoid overwriting local files. To download them somewhere else, specify the path to the desired directory (folder) in the `outpath` argument. 

```R
library(OCSdata)
```

### Starting at data import section:
The `raw_data` function will download the raw data files that will be imported into R.

```R
raw_data("ocs-bp-opioid-rural-urban", outpath = tempfile())
```
*image/gif showing downloaded data folder structure*

### For file formats that are easier to import:
The `simpler_import_data` function will download raw data files that have been converted to file formats that are easier to import into R, typically .csv. Some case studies offer this option when the original raw files require a more complicated import step. 

```R
simpler_import_data("ocs-bp-opioid-rural-urban", outpath = tempfile())
```

### For more data on this topic: 
The `extra_data` function will download raw data files that are not used in the case study, but are available for users to further analyze. 

```R
extra_data("ocs-bp-opioid-rural-urban", outpath = tempfile())
```
The data files downloaded by the last three methods can be imported into R using conventional data import methods.

### Starting at data exploration/wrangling sections: 
The `imported_data` function will download raw data files in the .rda format, meaning they've already been imported as R objects. 

```R
imported_data("ocs-bp-opioid-rural-urban", outpath = tempfile())
```
These files can be imported into R by either double clicking on the files in Rstudio or using the `load()` function. 
*show image/gif of clicking .rda files and give example of load() function*

### Starting at data visualization/analysis sections:
The `wrangled_data` function will download the data files that have already been wrangled and are ready to be processed. These come in both .csv and .rda formats. 

```R
wrangled_data("ocs-bp-opioid-rural-urban", outpath = tempfile())
```
These files can be imported with conventional import methods or the .rda methods shown above. 


### Download repository zip file: 
The `zip_ocs` function will download the all of the repository files as a .zip file and unzip them into the specified directory. 

```R
zip_ocs("ocs-bp-opioid-rural-urban", outpath = tempfile())
```

### Clone the case study GitHub repository: 
The `clone_ocs` function will clone the specified case study's GitHub repository with git and download the whole repository to the specified directory. 

```R
clone_ocs("ocs-bp-opioid-rural-urban", outpath = tempfile(), fork_repo = TRUE)
```

Setting fork_repo = TRUE will fork the repo first and then clone the fork, 
while FALSE will clone the repo directly from the Open Case Studies GitHub. 
The default is fork_repo = NA, which will fork or clone based on your repository 
permissions. This function requires your personal GitHub PAT to be registered in RStudio. 


*Note: To download the data into your current working directory, change the `outpath` argument to `getwd()`.*

Just change "ocs-bp-opioid-rural-urban" to the ID of the case study you are working on! (See above for list of IDs)
